robot_ipsa:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  arm1_position_controller:
    type: effort_controllers/JointPositionController
    joint: base_link_to_arm1
    pid: {p: 100.0, i: 0.01, d: 10.0}
  arm2_position_controller:
    type: effort_controllers/JointPositionController
    joint: arm1_to_arm2
    pid: {p: 100.0, i: 0.01, d: 10.0}
  arm3_position_controller:
    type: effort_controllers/JointPositionController
    joint: arm2_to_arm3
    pid: {p: 100.0, i: 0.01, d: 10.0}
